apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

helmCharts:
- name: prometheus
  repo: https://prometheus-community.github.io/helm-charts
  releaseName: prometheus
  version: 25.3.1   # Specify the version for staging environment
  valuesFile: ../../base/values.yaml