apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: {{ .Values.source.repoURL }}
    targetRevision: HEAD
    path: argocd
  destination:
    server: {{ .Values.destination.argocd }}
    namespace: argocd
  syncPolicy:
    syncOptions:
    - CreateNamespace=true  
    automated: 
      prune: true 
      selfHeal: true