# Important, only include if enabled through a values.yaml,
# which can be environment-specific
{{ if .Values.apps.nginx.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-{{ .Values.env }}
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: {{ .Values.apps.nginx.source.repoURL }}
    chart: {{ .Values.apps.nginx.source.chart }}
    targetRevision: {{ .Values.apps.nginx.source.targetRevision }}
    helm:
      ignoreMissingValueFiles: true
      valueFiles:
      - $values/{{ .Values.root.source.path }}/templates/apps/nginx/helmValues/values.yaml
      - $values/{{ .Values.root.source.path }}/templates/apps/nginx/helmValues/values-{{ .Values.env }}.yaml
  - repoURL: {{ .Values.root.source.repoURL }}
    targetRevision: HEAD
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.apps.nginx.namespace }}
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated: 
      prune: {{ .Values.appCommonSettings.spec.syncPolicy.automated.prune }} 
      selfHeal: {{ .Values.appCommonSettings.spec.syncPolicy.automated.selfHeal }}
{{ end }}