# Important, only include if enabled through a values.yaml,
# which can be environment-specific
{{ if .Values.apps.sealed-secrets-controller.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets-controller-{{ .Values.env }}
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: {{ .Values.apps.sealed-secrets-controller.source.repoURL }}
    chart: {{ .Values.apps.sealed-secrets-controller.source.chart }}
    targetRevision: {{ .Values.apps.sealed-secrets-controller.source.targetRevision }}
    helm:
      # So that if there is a missing environment values file
      # (eg. values-prod.yaml), it will default to just values.yaml
      ignoreMissingValueFiles: true 
      valueFiles:
      - $values/{{ .Values.root.source.path }}/templates/apps/sealed-secrets-controller/helmValues/values.yaml
      - $values/{{ .Values.root.source.path }}/templates/apps/sealed-secrets-controller/helmValues/values-{{ .Values.env }}.yaml
  - repoURL: {{ .Values.root.source.repoURL }}
    targetRevision: HEAD
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.apps.sealed-secrets-controller.namespace }}
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated: 
      prune: {{ .Values.appCommonSettings.spec.syncPolicy.automated.prune }} 
      selfHeal: {{ .Values.appCommonSettings.spec.syncPolicy.automated.selfHeal }}
{{ end }}