apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: root-appset
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
      - name: nginx
        displayName: nginx
        displayNamePostfix: -base
        path: apps/nginx/base
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{.displayName}}{{.displayNamePostfix}}'
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/alex-kumpula/ArgoCD-Test-3
        targetRevision: HEAD
        path: '{{.path}}'
      destination:
        server: '{{.url}}'
        namespace: argocd
      syncPolicy:
        syncOptions:
        - CreateNamespace=true  
        automated: 
          prune: true 
          selfHeal: true